-- ============================================================
-- Staffora HRMS — Oracle-Compatible DDL
-- Staffora: A Web-Based Human Resource Management System
-- Converted for Oracle SQL Developer Data Modeler 24.x
-- BSIT 2A | CCS05 | AUF College of Computer Studies | 2026
-- ============================================================

-- Dependency order: tables with no FKs first
-- DROP existing tables (reverse dependency order)
CREATE TABLE DEPARTMENTS (
  ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION CLOB DEFAULT NULL,
  LOCATION VARCHAR2(150) DEFAULT NULL,
  BUDGET NUMBER(15,2) DEFAULT 0.00,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID)
);

CREATE TABLE BENEFITS (
  ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION CLOB DEFAULT NULL,
  TYPE VARCHAR2(50) NOT NULL DEFAULT 'Other',
  VALUE NUMBER(12,2) NOT NULL DEFAULT 0.00,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_BENEFITS PRIMARY KEY (ID)
);

CREATE TABLE LMS_MODULES (
  ID NUMBER(11) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  DESCRIPTION CLOB DEFAULT NULL,
  TYPE VARCHAR2(10) NOT NULL DEFAULT 'document' CHECK (TYPE IN ('document','video','quiz')),
  DURATION_MINS NUMBER(11) NOT NULL DEFAULT 0,
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  CREATED_BY NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_LMS_MODULES PRIMARY KEY (ID),
  CONSTRAINT FK_LMS_MODULES_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_LMS_MODULES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE JOB_POSTINGS (
  ID NUMBER(11) NOT NULL,
  TITLE VARCHAR2(150) NOT NULL,
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  DESCRIPTION CLOB DEFAULT NULL,
  REQUIREMENTS CLOB DEFAULT NULL,
  SALARY_MIN NUMBER(12,2) DEFAULT NULL,
  SALARY_MAX NUMBER(12,2) DEFAULT NULL,
  LOCATION VARCHAR2(150) DEFAULT NULL,
  TYPE VARCHAR2(40) DEFAULT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Open' CHECK (STATUS IN ('Open','Closed','On Hold')),
  POSTED_BY NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_JOB_POSTINGS PRIMARY KEY (ID),
  CONSTRAINT FK_JOB_POSTINGS_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_JOB_POSTINGS_POSTED_BY FOREIGN KEY (POSTED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE USERS (
  ID NUMBER(11) NOT NULL,
  USERNAME VARCHAR2(80) NOT NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  PASSWORD VARCHAR2(255) NOT NULL,
  ROLE VARCHAR2(11) NOT NULL DEFAULT 'Employee' CHECK (ROLE IN ('Super Admin','Manager','Employee')),
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Active' CHECK (STATUS IN ('Active','Inactive')),
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_USERS PRIMARY KEY (ID),
  CONSTRAINT UQ_USERS_UQ_USER_EMAIL UNIQUE (EMAIL),
  CONSTRAINT FK_USERS_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL
);

CREATE TABLE POSITIONS (
  ID NUMBER(11) NOT NULL,
  TITLE VARCHAR2(100) NOT NULL,
  CODE VARCHAR2(20) DEFAULT NULL,
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  LEVEL NUMBER(11) DEFAULT 1,
  SALARY_MIN NUMBER(12,2) DEFAULT 0.00,
  SALARY_MAX NUMBER(12,2) DEFAULT 0.00,
  DESCRIPTION CLOB DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_POSITIONS PRIMARY KEY (ID),
  CONSTRAINT FK_POSITIONS_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL
);

CREATE TABLE WORK_RULES (
  ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  SCHEDULE_TYPE VARCHAR2(12) NOT NULL DEFAULT 'Basic' CHECK (SCHEDULE_TYPE IN ('Basic','Strict Flexi','Relax Flexi','Custom')),
  WORK_HOURS NUMBER(4,2) NOT NULL DEFAULT 8.00,
  BREAK_MINUTES NUMBER(11) NOT NULL DEFAULT 60,
  BREAK_COUNT NUMBER(11) NOT NULL DEFAULT 4,
  START_TIME VARCHAR2(8) DEFAULT '09:00:00',
  END_TIME VARCHAR2(8) DEFAULT '18:00:00',
  BUFFER_BEFORE NUMBER(11) DEFAULT 0,
  BUFFER_AFTER NUMBER(11) DEFAULT 0,
  CORE_START VARCHAR2(8) DEFAULT NULL,
  CORE_DURATION NUMBER(4,2) DEFAULT NULL,
  WORKING_DAYS VARCHAR2(20) DEFAULT '1,2,3,4,5',
  IS_DEFAULT NUMBER(1) NOT NULL DEFAULT 0,
  CREATED_BY NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_WORK_RULES PRIMARY KEY (ID),
  CONSTRAINT FK_WORK_RULES_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE EMPLOYEES (
  ID NUMBER(11) NOT NULL,
  USER_ID NUMBER(11) DEFAULT NULL,
  EMPLOYEE_NO VARCHAR2(30) DEFAULT NULL,
  FIRST_NAME VARCHAR2(80) NOT NULL,
  MIDDLE_NAME VARCHAR2(80) DEFAULT NULL,
  LAST_NAME VARCHAR2(80) NOT NULL,
  SUFFIX VARCHAR2(10) DEFAULT NULL,
  GENDER VARCHAR2(20) DEFAULT NULL,
  EMAIL VARCHAR2(150) DEFAULT NULL,
  PHONE VARCHAR2(30) DEFAULT NULL,
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  POSITION_ID NUMBER(11) DEFAULT NULL,
  WORK_RULE_ID NUMBER(11) DEFAULT NULL,
  JOB_TITLE VARCHAR2(100) DEFAULT NULL,
  EMPLOYMENT_TYPE VARCHAR2(11) NOT NULL DEFAULT 'Full-Time' CHECK (EMPLOYMENT_TYPE IN ('Full-Time','Part-Time','Contractual','Intern')),
  STATUS VARCHAR2(12) NOT NULL DEFAULT 'Probationary' CHECK (STATUS IN ('Regular','Probationary','Resigned','Terminated','On Leave')),
  HIRE_DATE date DEFAULT NULL,
  DATE_REGULARIZED date DEFAULT NULL,
  BASIC_SALARY NUMBER(12,2) NOT NULL DEFAULT 0.00,
  CIVIL_STATUS VARCHAR2(10) DEFAULT NULL CHECK (CIVIL_STATUS IN ('Single','Married','Widowed','Separated','Divorced')),
  DATE_OF_BIRTH date DEFAULT NULL,
  PLACE_OF_BIRTH VARCHAR2(150) DEFAULT NULL,
  NATIONALITY VARCHAR2(60) DEFAULT 'Filipino',
  SOLO_PARENT_ID VARCHAR2(50) DEFAULT NULL,
  BLOOD_TYPE VARCHAR2(5) DEFAULT NULL,
  HIGHEST_EDUCATION VARCHAR2(80) DEFAULT NULL,
  ADDRESS CLOB DEFAULT NULL,
  SSS_NO VARCHAR2(30) DEFAULT NULL,
  PHILHEALTH_NO VARCHAR2(30) DEFAULT NULL,
  PAGIBIG_NO VARCHAR2(30) DEFAULT NULL,
  TIN_NO VARCHAR2(30) DEFAULT NULL,
  BANK_NAME VARCHAR2(80) DEFAULT NULL,
  BANK_ACCOUNT_NUMBER VARCHAR2(40) DEFAULT NULL,
  EMERGENCY_CONTACT_NAME VARCHAR2(100) DEFAULT NULL,
  EMERGENCY_CONTACT_RELATIONSHIP VARCHAR2(60) DEFAULT NULL,
  EMERGENCY_CONTACT_PHONE VARCHAR2(30) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_EMPLOYEES PRIMARY KEY (ID),
  CONSTRAINT FK_EMPLOYEES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_EMPLOYEES_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_EMPLOYEES_POSITION_ID FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS (ID) ON DELETE SET NULL
);

CREATE TABLE ANNOUNCEMENTS (
  ID NUMBER(11) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB NOT NULL,
  POSTED_BY NUMBER(11) DEFAULT NULL,
  PRIORITY VARCHAR2(10) NOT NULL DEFAULT 'Medium' CHECK (PRIORITY IN ('Low','Medium','High','Urgent')),
  PINNED NUMBER(1) NOT NULL DEFAULT 0,
  TARGET_AUDIENCE VARCHAR2(50) NOT NULL DEFAULT 'All',
  IS_COMPANY_WIDE NUMBER(1) NOT NULL DEFAULT 1,
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_ANNOUNCEMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_ANNOUNCEMENTS_POSTED_BY FOREIGN KEY (POSTED_BY) REFERENCES USERS (ID) ON DELETE SET NULL,
  CONSTRAINT FK_ANNOUNCEMENTS_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL
);

CREATE TABLE ATTENDANCES (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  DATE date NOT NULL,
  CLOCK_IN VARCHAR2(8) DEFAULT NULL,
  CLOCK_OUT VARCHAR2(8) DEFAULT NULL,
  STATUS VARCHAR2(50) NOT NULL DEFAULT 'On Time',
  TOTAL_HOURS NUMBER(5,2) DEFAULT 0.00,
  NOTES CLOB DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  IP_ADDRESS VARCHAR2(45) DEFAULT NULL,
  CONSTRAINT PK_ATTENDANCES PRIMARY KEY (ID),
  CONSTRAINT FK_ATTENDANCES_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE AUDIT_LOGS (
  ID NUMBER(11) NOT NULL,
  USER_ID NUMBER(11) DEFAULT NULL,
  ACTION VARCHAR2(100) NOT NULL,
  MODULE VARCHAR2(80) NOT NULL,
  MODEL_ID NUMBER(11) DEFAULT NULL,
  DATA CLOB DEFAULT NULL,
  IP VARCHAR2(45) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID),
  CONSTRAINT FK_AUDIT_LOGS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE CANDIDATES (
  ID NUMBER(11) NOT NULL,
  JOB_ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(150) NOT NULL,
  EMAIL VARCHAR2(150) DEFAULT NULL,
  PHONE VARCHAR2(30) DEFAULT NULL,
  STAGE VARCHAR2(10) NOT NULL DEFAULT 'Applied' CHECK (STAGE IN ('Applied','Screening','Interview','Offer','Hired','Rejected')),
  EXPECTED_SALARY NUMBER(12,2) DEFAULT NULL,
  APPLIED_AT date DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_CANDIDATES PRIMARY KEY (ID),
  CONSTRAINT FK_CANDIDATES_JOB_ID FOREIGN KEY (JOB_ID) REFERENCES JOB_POSTINGS (ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_BENEFITS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  BENEFIT_ID NUMBER(11) NOT NULL,
  ENROLLED_AT date DEFAULT NULL,
  CONSTRAINT PK_EMPLOYEE_BENEFITS PRIMARY KEY (ID),
  CONSTRAINT UQ_EMPLOYEE_BENEFITS_UQ_EMPLOYEE_BENEFIT_UQ_EMP_BENEFIT UNIQUE (EMPLOYEE_ID,BENEFIT_ID),
  CONSTRAINT FK_EMPLOYEE_BENEFITS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_EMPLOYEE_BENEFITS_BENEFIT_ID FOREIGN KEY (BENEFIT_ID) REFERENCES BENEFITS (ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_DOCUMENTS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  DOCUMENT_TYPE VARCHAR2(100) NOT NULL,
  FILE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(500) NOT NULL,
  UPLOADED_AT NUMBER(11) NOT NULL DEFAULT 0,
  FILE_DATA mediumblob DEFAULT NULL,
  MIME_TYPE VARCHAR2(100) DEFAULT NULL,
  CONSTRAINT PK_EMPLOYEE_DOCUMENTS PRIMARY KEY (ID),
  CONSTRAINT FK_EMPLOYEE_DOCUMENTS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE FEEDBACKS (
  ID NUMBER(11) NOT NULL,
  SENDER_ID NUMBER(11) DEFAULT NULL,
  RECEIVER_ID NUMBER(11) NOT NULL,
  MESSAGE CLOB NOT NULL,
  CATEGORY VARCHAR2(12) NOT NULL DEFAULT 'positive' CHECK (CATEGORY IN ('positive','constructive','suggestion')),
  IS_ANONYMOUS NUMBER(1) NOT NULL DEFAULT 0,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_FEEDBACKS PRIMARY KEY (ID),
  CONSTRAINT FK_FEEDBACKS_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES EMPLOYEES (ID) ON DELETE SET NULL,
  CONSTRAINT FK_FEEDBACKS_RECEIVER_ID FOREIGN KEY (RECEIVER_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE HOLIDAYS (
  ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(150) NOT NULL,
  DATE date NOT NULL,
  TYPE VARCHAR2(19) NOT NULL DEFAULT 'Regular' CHECK (TYPE IN ('Regular','Special Non-Working','Special Working')),
  IS_RECURRING NUMBER(1) NOT NULL DEFAULT 0,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_HOLIDAYS PRIMARY KEY (ID)
);

CREATE TABLE LEAVE_BALANCES (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  YEAR year(4) NOT NULL,
  SIL_ACCRUED NUMBER(5,2) NOT NULL DEFAULT 0.00,
  SIL_MANUAL_OVERRIDE NUMBER(1) NOT NULL DEFAULT 0,
  SIL_USED NUMBER(5,2) NOT NULL DEFAULT 0.00,
  SIL_CARRIED_OVER NUMBER(5,2) NOT NULL DEFAULT 0.00,
  BIRTHDAY_USED NUMBER(1) NOT NULL DEFAULT 0,
  BEREAVEMENT_USED NUMBER(3,1) NOT NULL DEFAULT 0.0,
  PATERNITY_USED NUMBER(3,1) NOT NULL DEFAULT 0.0,
  MATERNITY_USED NUMBER(11) NOT NULL DEFAULT 0,
  SOLO_PARENT_USED NUMBER(3,1) NOT NULL DEFAULT 0.0,
  SPECIAL_WOMEN_USED NUMBER(11) NOT NULL DEFAULT 0,
  VAWC_USED NUMBER(3,1) NOT NULL DEFAULT 0.0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_LEAVE_BALANCES PRIMARY KEY (ID),
  CONSTRAINT UQ_LEAVE_BALANCES_UQ_LEAVE_BALANCE_UK_EMP_YEAR UNIQUE (EMPLOYEE_ID,YEAR),
  CONSTRAINT FK_LEAVE_BALANCES_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE LEAVE_REQUESTS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  LEAVE_TYPE VARCHAR2(60) NOT NULL,
  START_DATE date NOT NULL,
  END_DATE date NOT NULL,
  DAYS NUMBER(4,1) NOT NULL DEFAULT 1.0,
  REASON CLOB DEFAULT NULL,
  DOC_PATH VARCHAR2(255) DEFAULT NULL,
  DEDUCTED_FROM VARCHAR2(30) DEFAULT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Pending' CHECK (STATUS IN ('Pending','Approved','Denied')),
  APPROVED_BY NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_LEAVE_REQUESTS PRIMARY KEY (ID),
  CONSTRAINT FK_LEAVE_REQUESTS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_LEAVE_REQUESTS_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE LMS_ENROLLMENTS (
  ID NUMBER(11) NOT NULL,
  MODULE_ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  PROGRESS NUMBER(1) NOT NULL DEFAULT 0,
  STATUS VARCHAR2(11) NOT NULL DEFAULT 'Not Started' CHECK (STATUS IN ('Not Started','In Progress','Completed')),
  COMPLETED_AT NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_LMS_ENROLLMENTS PRIMARY KEY (ID),
  CONSTRAINT UQ_LMS_ENROLLMENTS_UQ_LMS_ENROLLMENT_UQ_LMS_ENROLL UNIQUE (MODULE_ID,EMPLOYEE_ID),
  CONSTRAINT FK_LMS_ENROLLMENTS_MODULE_ID FOREIGN KEY (MODULE_ID) REFERENCES LMS_MODULES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_LMS_ENROLLMENTS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE ONBOARDING_TASKS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  TASK_NAME VARCHAR2(200) NOT NULL,
  STAGE VARCHAR2(12) NOT NULL DEFAULT 'Pre-boarding' CHECK (STAGE IN ('Pre-boarding','Week 1','Week 2','Integration')),
  STATUS VARCHAR2(11) NOT NULL DEFAULT 'Not Started' CHECK (STATUS IN ('Not Started','In Progress','Completed','On Hold')),
  DUE_DATE date DEFAULT NULL,
  NOTES CLOB DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_ONBOARDING_TASKS PRIMARY KEY (ID),
  CONSTRAINT FK_ONBOARDING_TASKS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE PAYROLLS (
  ID NUMBER(11) NOT NULL,
  PERIOD_LABEL VARCHAR2(100) NOT NULL,
  PERIOD_START date NOT NULL,
  PERIOD_END date NOT NULL,
  PAY_DATE date NOT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Draft' CHECK (STATUS IN ('Draft','Processed','Released')),
  CREATED_BY NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_PAYROLLS PRIMARY KEY (ID),
  CONSTRAINT FK_PAYROLLS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE PERSONNEL_ACTIONS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  TYPE VARCHAR2(17) NOT NULL CHECK (TYPE IN ('Promotion','Demotion','Salary Adjustment','Transfer','Resignation','Termination','Other')),
  EFFECTIVE_DATE date NOT NULL,
  OLD_VALUE VARCHAR2(200) DEFAULT NULL,
  NEW_VALUE VARCHAR2(200) DEFAULT NULL,
  REMARKS CLOB DEFAULT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Approved' CHECK (STATUS IN ('Pending','Approved','Rejected')),
  CREATED_BY NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_PERSONNEL_ACTIONS PRIMARY KEY (ID),
  CONSTRAINT FK_PERSONNEL_ACTIONS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PERSONNEL_ACTIONS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE PROJECTS (
  ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(150) NOT NULL,
  OWNER_ID NUMBER(11) DEFAULT NULL,
  DEPARTMENT_ID NUMBER(11) DEFAULT NULL,
  DESCRIPTION CLOB DEFAULT NULL,
  START_DATE date DEFAULT NULL,
  DEADLINE date DEFAULT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Active' CHECK (STATUS IN ('Active','On Hold','Completed','Cancelled')),
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_PROJECTS PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECTS_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES EMPLOYEES (ID) ON DELETE SET NULL,
  CONSTRAINT FK_PROJECTS_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE SET NULL
);

CREATE TABLE SYSTEM_NOTIFICATIONS (
  ID NUMBER(11) NOT NULL,
  USER_ID NUMBER(11) NOT NULL,
  TYPE VARCHAR2(10) NOT NULL DEFAULT 'info' CHECK (TYPE IN ('info','success','warning','danger')),
  TITLE VARCHAR2(200) NOT NULL,
  MESSAGE CLOB NOT NULL,
  LINK VARCHAR2(500) DEFAULT NULL,
  IS_READ NUMBER(1) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_SYSTEM_NOTIFICATIONS PRIMARY KEY (ID),
  CONSTRAINT FK_SYSTEM_NOTIFICATIONS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE SYSTEM_SETTINGS (
  ID NUMBER(11) NOT NULL,
  KEY VARCHAR2(80) NOT NULL,
  VALUE CLOB DEFAULT NULL,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_SYSTEM_SETTINGS PRIMARY KEY (ID),
  CONSTRAINT UQ_SYSTEM_SETTINGS_UQ_SYSTEM_SETTING_KEY UNIQUE (KEY)
);

CREATE TABLE TIMELOG_DISPUTES (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  DISPUTE_DATE date NOT NULL,
  ORIGINAL_CLOCK_IN VARCHAR2(8) DEFAULT NULL,
  ORIGINAL_CLOCK_OUT VARCHAR2(8) DEFAULT NULL,
  CORRECTED_CLOCK_IN VARCHAR2(8) DEFAULT NULL,
  CORRECTED_CLOCK_OUT VARCHAR2(8) DEFAULT NULL,
  BREAK_MINUTES NUMBER(11) DEFAULT 60,
  DISPUTE_TYPE VARCHAR2(18) NOT NULL DEFAULT 'Timelog Correction' CHECK (DISPUTE_TYPE IN ('Timelog Correction','Schedule Issue','Generic')),
  REASON CLOB DEFAULT NULL,
  DOC_PATH VARCHAR2(255) DEFAULT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Pending' CHECK (STATUS IN ('Pending','Approved','Denied')),
  REVIEWED_BY NUMBER(11) DEFAULT NULL,
  REVIEWED_AT NUMBER(11) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_TIMELOG_DISPUTES PRIMARY KEY (ID),
  CONSTRAINT FK_TIMELOG_DISPUTES_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_TIMELOG_DISPUTES_REVIEWED_BY FOREIGN KEY (REVIEWED_BY) REFERENCES USERS (ID) ON DELETE SET NULL
);

CREATE TABLE PAYSLIPS (
  ID NUMBER(11) NOT NULL,
  PAYROLL_ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  BASIC_SALARY NUMBER(12,2) NOT NULL DEFAULT 0.00,
  ALLOWANCES NUMBER(12,2) NOT NULL DEFAULT 0.00,
  OVERTIME_PAY NUMBER(12,2) NOT NULL DEFAULT 0.00,
  GROSS_PAY NUMBER(12,2) NOT NULL DEFAULT 0.00,
  SSS NUMBER(10,2) NOT NULL DEFAULT 0.00,
  PHIL_HEALTH NUMBER(10,2) NOT NULL DEFAULT 0.00,
  PAG_IBIG NUMBER(10,2) NOT NULL DEFAULT 0.00,
  INCOME_TAX NUMBER(10,2) NOT NULL DEFAULT 0.00,
  TOTAL_DEDUCTIONS NUMBER(12,2) NOT NULL DEFAULT 0.00,
  NET_PAY NUMBER(12,2) NOT NULL DEFAULT 0.00,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Processed' CHECK (STATUS IN ('Processed','Released','Cancelled')),
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_PAYSLIPS PRIMARY KEY (ID),
  CONSTRAINT UQ_PAYSLIPS_UQ_PAYSLIP_UQ_PAYSLIP UNIQUE (PAYROLL_ID,EMPLOYEE_ID),
  CONSTRAINT FK_PAYSLIPS_PAYROLL_ID FOREIGN KEY (PAYROLL_ID) REFERENCES PAYROLLS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PAYSLIPS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE PROJECT_MEMBERS (
  ID NUMBER(11) NOT NULL,
  PROJECT_ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  CONSTRAINT PK_PROJECT_MEMBERS PRIMARY KEY (ID),
  CONSTRAINT UQ_PROJECT_MEMBERS_UQ_PROJECT_MEMBER_UQ_PROJ_MEMBER UNIQUE (PROJECT_ID,EMPLOYEE_ID),
  CONSTRAINT FK_PROJECT_MEMBERS_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PROJECT_MEMBERS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE PROJECT_TASKS (
  ID NUMBER(11) NOT NULL,
  PROJECT_ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) DEFAULT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  PRIORITY VARCHAR2(10) NOT NULL DEFAULT 'Medium' CHECK (PRIORITY IN ('Low','Medium','High','Critical')),
  STATUS VARCHAR2(11) NOT NULL DEFAULT 'To Do' CHECK (STATUS IN ('To Do','In Progress','Completed','Cancelled')),
  PROGRESS NUMBER(1) NOT NULL DEFAULT 0,
  DUE_DATE date DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_PROJECT_TASKS PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_TASKS_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PROJECT_TASKS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE SET NULL
);

CREATE TABLE SHIFTS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  DATE date NOT NULL,
  START_TIME VARCHAR2(8) NOT NULL,
  END_TIME VARCHAR2(8) NOT NULL,
  SHIFT_NAME VARCHAR2(80) DEFAULT NULL,
  WORK_RULE_ID NUMBER(11) DEFAULT NULL,
  BREAK_MINUTES NUMBER(11) DEFAULT 60,
  BREAK_START_TIME VARCHAR2(8) DEFAULT NULL,
  BREAK_END_TIME VARCHAR2(8) DEFAULT NULL,
  TYPE VARCHAR2(10) NOT NULL DEFAULT 'Onsite' CHECK (TYPE IN ('Onsite','Remote','Hybrid')),
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Scheduled' CHECK (STATUS IN ('Scheduled','Completed','Missed','Cancelled')),
  PUBLISHED NUMBER(1) NOT NULL DEFAULT 1,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_SHIFTS PRIMARY KEY (ID),
  CONSTRAINT UQ_SHIFTS_UQ_SHIFT_UQ_SHIFT_EMP_DATE UNIQUE (EMPLOYEE_ID,DATE),
  CONSTRAINT FK_SHIFTS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE
);

CREATE TABLE EMPLOYEE_DOC_CHECKLISTS (
  ID NUMBER(11) NOT NULL,
  EMPLOYEE_ID NUMBER(11) NOT NULL,
  DOCUMENT_TYPE VARCHAR2(100) NOT NULL,
  STATUS VARCHAR2(10) NOT NULL DEFAULT 'Pending' CHECK (STATUS IN ('Pending','Submitted','Approved','Waived')),
  DOCUMENT_ID NUMBER(11) DEFAULT NULL,
  NOTES VARCHAR2(255) DEFAULT NULL,
  CREATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  UPDATED_AT NUMBER(11) NOT NULL DEFAULT 0,
  CONSTRAINT PK_EMPLOYEE_DOC_CHECKLISTS PRIMARY KEY (ID),
  CONSTRAINT FK_EMPLOYEE_DOC_CHECKLISTS_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID) ON DELETE CASCADE,
  CONSTRAINT FK_EMPLOYEE_DOC_CHECKLISTS_DOCUMENT_ID FOREIGN KEY (DOCUMENT_ID) REFERENCES EMPLOYEE_DOCUMENTS (ID) ON DELETE SET NULL
);
