-- ============================================================
--  Staffora HRMS v3 — Oracle DDL  (Part 1 / 2)
--  Relational Model | Oracle Database 21c
--  Conventions: Plural UPPERCASE tables | UPPERCASE columns
--               _PK  _FK  _UQ  _CHK constraint suffixes
-- ============================================================

-- ============================================================
-- 1. DEPARTMENTS
-- ============================================================
CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID   NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  DEPT_NAME       VARCHAR2(100) NOT NULL,
  DESCRIPTION     CLOB,
  LOCATION        VARCHAR2(150),
  BUDGET          NUMBER(15,2)  DEFAULT 0,
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT DEPARTMENTS_PK        PRIMARY KEY (DEPARTMENT_ID),
  CONSTRAINT DEPARTMENTS_NAME_UQ   UNIQUE      (DEPT_NAME)
);

-- ============================================================
-- 2. USER_ACCOUNTS
-- ============================================================
CREATE TABLE USER_ACCOUNTS (
  USER_ID         NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  USERNAME        VARCHAR2(80)  NOT NULL,
  EMAIL           VARCHAR2(150) NOT NULL,
  PASSWORD        VARCHAR2(255) NOT NULL,
  ROLE            VARCHAR2(20)  DEFAULT 'Employee' NOT NULL,
  STATUS          VARCHAR2(10)  DEFAULT 'Active'   NOT NULL,
  DEPARTMENT_ID   NUMBER(10),
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT USER_ACCOUNTS_PK          PRIMARY KEY (USER_ID),
  CONSTRAINT USER_ACCOUNTS_EMAIL_UQ    UNIQUE      (EMAIL),
  CONSTRAINT USER_ACCOUNTS_UNAME_UQ    UNIQUE      (USERNAME),
  CONSTRAINT USER_ACCOUNTS_ROLE_CHK    CHECK       (ROLE   IN ('Super Admin','Manager','Employee')),
  CONSTRAINT USER_ACCOUNTS_STATUS_CHK  CHECK       (STATUS IN ('Active','Inactive')),
  CONSTRAINT USER_ACCOUNTS_DEPT_FK     FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
);

-- ============================================================
-- 3. POSITIONS
-- ============================================================
CREATE TABLE POSITIONS (
  POSITION_ID     NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  TITLE           VARCHAR2(100) NOT NULL,
  DEPARTMENT_ID   NUMBER(10),
  SALARY_MIN      NUMBER(12,2)  DEFAULT 0,
  SALARY_MAX      NUMBER(12,2)  DEFAULT 0,
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT POSITIONS_PK       PRIMARY KEY (POSITION_ID),
  CONSTRAINT POSITIONS_DEPT_FK  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
);

-- ============================================================
-- 4. EMPLOYEES
-- ============================================================
CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID                    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  USER_ID                        NUMBER(10),
  EMPLOYEE_NO                    VARCHAR2(30),
  FIRST_NAME                     VARCHAR2(80)  NOT NULL,
  MIDDLE_NAME                    VARCHAR2(80),
  LAST_NAME                      VARCHAR2(80)  NOT NULL,
  SUFFIX                         VARCHAR2(10),
  GENDER                         VARCHAR2(20),
  EMAIL                          VARCHAR2(150),
  PHONE                          VARCHAR2(30),
  DEPARTMENT_ID                  NUMBER(10),
  POSITION_ID                    NUMBER(10),
  JOB_TITLE                      VARCHAR2(100),
  EMPLOYMENT_TYPE                VARCHAR2(20)  DEFAULT 'Full-Time' NOT NULL,
  STATUS                         VARCHAR2(20)  DEFAULT 'Probationary' NOT NULL,
  HIRE_DATE                      DATE,
  BASIC_SALARY                   NUMBER(12,2)  DEFAULT 0 NOT NULL,
  CIVIL_STATUS                   VARCHAR2(15),
  DATE_OF_BIRTH                  DATE,
  PLACE_OF_BIRTH                 VARCHAR2(150),
  NATIONALITY                    VARCHAR2(60)  DEFAULT 'Filipino',
  BLOOD_TYPE                     VARCHAR2(5),
  HIGHEST_EDUCATION              VARCHAR2(80),
  ADDRESS                        CLOB,
  SSS_NO                         VARCHAR2(30),
  PHILHEALTH_NO                  VARCHAR2(30),
  PAGIBIG_NO                     VARCHAR2(30),
  TIN_NO                         VARCHAR2(30),
  BANK_NAME                      VARCHAR2(80),
  BANK_ACCOUNT_NUMBER            VARCHAR2(40),
  EMERGENCY_CONTACT_NAME         VARCHAR2(100),
  EMERGENCY_CONTACT_RELATIONSHIP VARCHAR2(60),
  EMERGENCY_CONTACT_PHONE        VARCHAR2(30),
  CREATED_AT                     NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT                     NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT EMPLOYEES_PK              PRIMARY KEY (EMPLOYEE_ID),
  CONSTRAINT EMPLOYEES_EMP_TYPE_CHK    CHECK (EMPLOYMENT_TYPE IN ('Full-Time','Part-Time','Contractual','Intern')),
  CONSTRAINT EMPLOYEES_STATUS_CHK      CHECK (STATUS          IN ('Regular','Probationary','Resigned','Terminated','On Leave')),
  CONSTRAINT EMPLOYEES_CIVIL_CHK       CHECK (CIVIL_STATUS IS NULL OR CIVIL_STATUS IN ('Single','Married','Widowed','Separated','Divorced')),
  CONSTRAINT EMPLOYEES_USER_FK         FOREIGN KEY (USER_ID)       REFERENCES USER_ACCOUNTS(USER_ID)   ON DELETE SET NULL,
  CONSTRAINT EMPLOYEES_DEPT_FK         FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL,
  CONSTRAINT EMPLOYEES_POS_FK          FOREIGN KEY (POSITION_ID)   REFERENCES POSITIONS(POSITION_ID)   ON DELETE SET NULL
);

-- ============================================================
-- 5. SYSTEM_SETTINGS
-- ============================================================
CREATE TABLE SYSTEM_SETTINGS (
  SETTING_ID   NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  KEY_NAME     VARCHAR2(80) NOT NULL,
  VALUE        CLOB,
  UPDATED_AT   NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT SYSTEM_SETTINGS_PK       PRIMARY KEY (SETTING_ID),
  CONSTRAINT SYSTEM_SETTINGS_KEY_UQ   UNIQUE      (KEY_NAME)
);

-- ============================================================
-- 6. ATTENDANCES
-- ============================================================
CREATE TABLE ATTENDANCES (
  ATTENDANCE_ID  NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID    NUMBER(10)   NOT NULL,
  ATT_DATE       DATE         NOT NULL,
  CLOCK_IN       VARCHAR2(8),
  CLOCK_OUT      VARCHAR2(8),
  STATUS         VARCHAR2(20) DEFAULT 'On Time' NOT NULL,
  TOTAL_HOURS    NUMBER(5,2)  DEFAULT 0,
  NOTES          CLOB,
  CREATED_AT     NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT ATTENDANCES_PK           PRIMARY KEY (ATTENDANCE_ID),
  CONSTRAINT ATTENDANCES_EMP_DATE_UQ  UNIQUE      (EMPLOYEE_ID, ATT_DATE),
  CONSTRAINT ATTENDANCES_STATUS_CHK   CHECK       (STATUS IN ('On Time','Late','Absent','Half-Day')),
  CONSTRAINT ATTENDANCES_EMP_FK       FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 7. SHIFTS
-- ============================================================
CREATE TABLE SHIFTS (
  SHIFT_ID      NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)   NOT NULL,
  SHIFT_DATE    DATE         NOT NULL,
  START_TIME    VARCHAR2(8)  NOT NULL,
  END_TIME      VARCHAR2(8)  NOT NULL,
  SHIFT_NAME    VARCHAR2(80),
  SHIFT_TYPE    VARCHAR2(10) DEFAULT 'Onsite' NOT NULL,
  STATUS        VARCHAR2(15) DEFAULT 'Scheduled' NOT NULL,
  PUBLISHED     NUMBER(1)    DEFAULT 1 NOT NULL,
  CREATED_AT    NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT SHIFTS_PK          PRIMARY KEY (SHIFT_ID),
  CONSTRAINT SHIFTS_EMP_DATE_UQ UNIQUE      (EMPLOYEE_ID, SHIFT_DATE),
  CONSTRAINT SHIFTS_TYPE_CHK    CHECK       (SHIFT_TYPE IN ('Onsite','Remote','Hybrid')),
  CONSTRAINT SHIFTS_STATUS_CHK  CHECK       (STATUS     IN ('Scheduled','Completed','Missed','Cancelled')),
  CONSTRAINT SHIFTS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 8. LEAVE_REQUESTS
-- ============================================================
CREATE TABLE LEAVE_REQUESTS (
  LEAVE_REQUEST_ID  NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID       NUMBER(10)   NOT NULL,
  LEAVE_TYPE        VARCHAR2(60) NOT NULL,
  START_DATE        DATE         NOT NULL,
  END_DATE          DATE         NOT NULL,
  DAYS              NUMBER(4,1)  DEFAULT 1 NOT NULL,
  REASON            CLOB,
  STATUS            VARCHAR2(10) DEFAULT 'Pending' NOT NULL,
  APPROVED_BY       NUMBER(10),
  CREATED_AT        NUMBER(12)   DEFAULT 0 NOT NULL,
  UPDATED_AT        NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT LEAVE_REQUESTS_PK          PRIMARY KEY (LEAVE_REQUEST_ID),
  CONSTRAINT LEAVE_REQUESTS_STATUS_CHK  CHECK       (STATUS IN ('Pending','Approved','Denied')),
  CONSTRAINT LEAVE_REQUESTS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)    ON DELETE CASCADE,
  CONSTRAINT LEAVE_REQUESTS_APPROVER_FK FOREIGN KEY (APPROVED_BY) REFERENCES USER_ACCOUNTS(USER_ID)   ON DELETE SET NULL
);

-- ============================================================
-- 9. ANNOUNCEMENTS
-- ============================================================
CREATE TABLE ANNOUNCEMENTS (
  ANNOUNCEMENT_ID   NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  TITLE             VARCHAR2(200) NOT NULL,
  CONTENT           CLOB          NOT NULL,
  POSTED_BY         NUMBER(10),
  PRIORITY          VARCHAR2(10)  DEFAULT 'Medium' NOT NULL,
  PINNED            NUMBER(1)     DEFAULT 0 NOT NULL,
  TARGET_AUDIENCE   VARCHAR2(50)  DEFAULT 'All' NOT NULL,
  DEPARTMENT_ID     NUMBER(10),
  CREATED_AT        NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT        NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT ANNOUNCEMENTS_PK            PRIMARY KEY (ANNOUNCEMENT_ID),
  CONSTRAINT ANNOUNCEMENTS_PRIORITY_CHK  CHECK       (PRIORITY IN ('Low','Medium','High','Urgent')),
  CONSTRAINT ANNOUNCEMENTS_USER_FK       FOREIGN KEY (POSTED_BY)     REFERENCES USER_ACCOUNTS(USER_ID)      ON DELETE SET NULL,
  CONSTRAINT ANNOUNCEMENTS_DEPT_FK       FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)  ON DELETE SET NULL
);

-- ============================================================
-- 10. HOLIDAYS
-- ============================================================
CREATE TABLE HOLIDAYS (
  HOLIDAY_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  HOLIDAY_NAME  VARCHAR2(150) NOT NULL,
  HOLIDAY_DATE  DATE          NOT NULL,
  HOLIDAY_TYPE  VARCHAR2(30)  DEFAULT 'Regular' NOT NULL,
  IS_RECURRING  NUMBER(1)     DEFAULT 0 NOT NULL,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT HOLIDAYS_PK        PRIMARY KEY (HOLIDAY_ID),
  CONSTRAINT HOLIDAYS_TYPE_CHK  CHECK       (HOLIDAY_TYPE IN ('Regular','Special Non-Working','Special Working'))
);

-- ============================================================
-- 11. PAYROLLS
-- ============================================================
CREATE TABLE PAYROLLS (
  PAYROLL_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  PERIOD_LABEL  VARCHAR2(100) NOT NULL,
  PERIOD_START  DATE          NOT NULL,
  PERIOD_END    DATE          NOT NULL,
  PAY_DATE      DATE          NOT NULL,
  STATUS        VARCHAR2(15)  DEFAULT 'Draft' NOT NULL,
  CREATED_BY    NUMBER(10),
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT PAYROLLS_PK          PRIMARY KEY (PAYROLL_ID),
  CONSTRAINT PAYROLLS_STATUS_CHK  CHECK       (STATUS IN ('Draft','Processed','Released')),
  CONSTRAINT PAYROLLS_USER_FK     FOREIGN KEY (CREATED_BY) REFERENCES USER_ACCOUNTS(USER_ID) ON DELETE SET NULL
);

-- ============================================================
-- 12. PAYSLIPS
-- ============================================================
CREATE TABLE PAYSLIPS (
  PAYSLIP_ID        NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  PAYROLL_ID        NUMBER(10)   NOT NULL,
  EMPLOYEE_ID       NUMBER(10)   NOT NULL,
  BASIC_SALARY      NUMBER(12,2) DEFAULT 0 NOT NULL,
  ALLOWANCES        NUMBER(12,2) DEFAULT 0 NOT NULL,
  OVERTIME_PAY      NUMBER(12,2) DEFAULT 0 NOT NULL,
  GROSS_PAY         NUMBER(12,2) DEFAULT 0 NOT NULL,
  SSS               NUMBER(10,2) DEFAULT 0 NOT NULL,
  PHIL_HEALTH       NUMBER(10,2) DEFAULT 0 NOT NULL,
  PAG_IBIG          NUMBER(10,2) DEFAULT 0 NOT NULL,
  INCOME_TAX        NUMBER(10,2) DEFAULT 0 NOT NULL,
  TOTAL_DEDUCTIONS  NUMBER(12,2) DEFAULT 0 NOT NULL,
  NET_PAY           NUMBER(12,2) DEFAULT 0 NOT NULL,
  STATUS            VARCHAR2(15) DEFAULT 'Processed' NOT NULL,
  CREATED_AT        NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT PAYSLIPS_PK            PRIMARY KEY (PAYSLIP_ID),
  CONSTRAINT PAYSLIPS_EMP_PAYRL_UQ  UNIQUE      (PAYROLL_ID, EMPLOYEE_ID),
  CONSTRAINT PAYSLIPS_STATUS_CHK    CHECK       (STATUS IN ('Processed','Released','Cancelled')),
  CONSTRAINT PAYSLIPS_PAYROLL_FK    FOREIGN KEY (PAYROLL_ID)  REFERENCES PAYROLLS(PAYROLL_ID)    ON DELETE CASCADE,
  CONSTRAINT PAYSLIPS_EMP_FK        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)  ON DELETE CASCADE
);

-- ============================================================
-- 13. FEEDBACK
-- ============================================================
CREATE TABLE FEEDBACK (
  FEEDBACK_ID   NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  SENDER_ID     NUMBER(10),
  RECEIVER_ID   NUMBER(10)   NOT NULL,
  MESSAGE       CLOB         NOT NULL,
  CATEGORY      VARCHAR2(20) DEFAULT 'positive' NOT NULL,
  IS_ANONYMOUS  NUMBER(1)    DEFAULT 0 NOT NULL,
  CREATED_AT    NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT FEEDBACK_PK           PRIMARY KEY (FEEDBACK_ID),
  CONSTRAINT FEEDBACK_CAT_CHK      CHECK       (CATEGORY IN ('positive','constructive','suggestion')),
  CONSTRAINT FEEDBACK_SENDER_FK    FOREIGN KEY (SENDER_ID)   REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL,
  CONSTRAINT FEEDBACK_RECEIVER_FK  FOREIGN KEY (RECEIVER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 14. PERSONNEL_ACTIONS
-- ============================================================
CREATE TABLE PERSONNEL_ACTIONS (
  PERSONNEL_ACTION_ID  NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID          NUMBER(10)    NOT NULL,
  ACTION_TYPE          VARCHAR2(25)  NOT NULL,
  EFFECTIVE_DATE       DATE          NOT NULL,
  OLD_VALUE            VARCHAR2(200),
  NEW_VALUE            VARCHAR2(200),
  REMARKS              CLOB,
  STATUS               VARCHAR2(10)  DEFAULT 'Approved' NOT NULL,
  CREATED_BY           NUMBER(10),
  CREATED_AT           NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT           NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT PERSONNEL_ACTIONS_PK          PRIMARY KEY (PERSONNEL_ACTION_ID),
  CONSTRAINT PERSONNEL_ACTIONS_TYPE_CHK    CHECK       (ACTION_TYPE IN ('Promotion','Demotion','Salary Adjustment','Transfer','Resignation','Termination','Other')),
  CONSTRAINT PERSONNEL_ACTIONS_STATUS_CHK  CHECK       (STATUS      IN ('Pending','Approved','Rejected')),
  CONSTRAINT PERSONNEL_ACTIONS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)    ON DELETE CASCADE,
  CONSTRAINT PERSONNEL_ACTIONS_USER_FK     FOREIGN KEY (CREATED_BY)  REFERENCES USER_ACCOUNTS(USER_ID)    ON DELETE SET NULL
);

-- ============================================================
-- INDEXES — Part 1
-- ============================================================
CREATE INDEX EMPLOYEES_USER_ID_IDX   ON EMPLOYEES(USER_ID);
CREATE INDEX EMPLOYEES_DEPT_IDX      ON EMPLOYEES(DEPARTMENT_ID);
CREATE INDEX ATTENDANCES_DATE_IDX    ON ATTENDANCES(ATT_DATE);
CREATE INDEX SHIFTS_DATE_IDX         ON SHIFTS(SHIFT_DATE);
CREATE INDEX LEAVE_REQ_EMP_IDX       ON LEAVE_REQUESTS(EMPLOYEE_ID);
CREATE INDEX LEAVE_REQ_STATUS_IDX    ON LEAVE_REQUESTS(STATUS);
CREATE INDEX PAYSLIPS_EMP_IDX        ON PAYSLIPS(EMPLOYEE_ID);
CREATE INDEX PERSONNEL_ACT_EMP_IDX   ON PERSONNEL_ACTIONS(EMPLOYEE_ID);
-- ============================================================
--  Staffora HRMS v3 — Oracle DDL (Part 2 / 2)
--  Relational Model | Oracle Database 21c
-- ============================================================

-- ============================================================
-- 15. BENEFITS
-- ============================================================
CREATE TABLE BENEFITS (
  BENEFIT_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  BENEFIT_NAME  VARCHAR2(100) NOT NULL,
  DESCRIPTION   CLOB,
  BENEFIT_TYPE  VARCHAR2(50)  DEFAULT 'Other' NOT NULL,
  VALUE         NUMBER(12,2)  DEFAULT 0 NOT NULL,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT BENEFITS_PK           PRIMARY KEY (BENEFIT_ID),
  CONSTRAINT BENEFITS_NAME_UQ      UNIQUE      (BENEFIT_NAME),
  CONSTRAINT BENEFITS_TYPE_CHK     CHECK       (BENEFIT_TYPE IN ('Health','Government','Bonus','Allowance','Other'))
);

-- ============================================================
-- 16. EMPLOYEE_BENEFITS
-- ============================================================
CREATE TABLE EMPLOYEE_BENEFITS (
  EMP_BENEFIT_ID  NUMBER(10) GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID     NUMBER(10) NOT NULL,
  BENEFIT_ID      NUMBER(10) NOT NULL,
  ENROLLED_AT     DATE,
  CONSTRAINT EMPLOYEE_BENEFITS_PK      PRIMARY KEY (EMP_BENEFIT_ID),
  CONSTRAINT EMPLOYEE_BENEFITS_UQ      UNIQUE      (EMPLOYEE_ID, BENEFIT_ID),
  CONSTRAINT EMPLOYEE_BENEFITS_EMP_FK  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE,
  CONSTRAINT EMPLOYEE_BENEFITS_BEN_FK  FOREIGN KEY (BENEFIT_ID)  REFERENCES BENEFITS(BENEFIT_ID)   ON DELETE CASCADE
);

-- ============================================================
-- 17. ONBOARDING_TASKS
-- ============================================================
CREATE TABLE ONBOARDING_TASKS (
  TASK_ID       NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)    NOT NULL,
  TASK_NAME     VARCHAR2(200) NOT NULL,
  STAGE         VARCHAR2(20)  DEFAULT 'Pre-boarding' NOT NULL,
  STATUS        VARCHAR2(20)  DEFAULT 'Not Started'  NOT NULL,
  DUE_DATE      DATE,
  NOTES         CLOB,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT ONBOARDING_TASKS_PK          PRIMARY KEY (TASK_ID),
  CONSTRAINT ONBOARDING_TASKS_STAGE_CHK   CHECK       (STAGE  IN ('Pre-boarding','Week 1','Week 2','Integration')),
  CONSTRAINT ONBOARDING_TASKS_STATUS_CHK  CHECK       (STATUS IN ('Not Started','In Progress','Completed','On Hold')),
  CONSTRAINT ONBOARDING_TASKS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 18. EMPLOYEE_DOCUMENTS
-- ============================================================
CREATE TABLE EMPLOYEE_DOCUMENTS (
  DOCUMENT_ID   NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)    NOT NULL,
  DOCUMENT_TYPE VARCHAR2(100) NOT NULL,
  FILE_NAME     VARCHAR2(255) NOT NULL,
  FILE_PATH     VARCHAR2(500) NOT NULL,
  UPLOADED_AT   NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT EMPLOYEE_DOCUMENTS_PK      PRIMARY KEY (DOCUMENT_ID),
  CONSTRAINT EMPLOYEE_DOCUMENTS_EMP_FK  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 19. EMPLOYEE_DOC_CHECKLISTS
-- ============================================================
CREATE TABLE EMPLOYEE_DOC_CHECKLISTS (
  CHECKLIST_ID  NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)    NOT NULL,
  DOCUMENT_TYPE VARCHAR2(100) NOT NULL,
  STATUS        VARCHAR2(15)  DEFAULT 'Pending' NOT NULL,
  DOCUMENT_ID   NUMBER(10),
  NOTES         VARCHAR2(255),
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT EMP_DOC_CHECKLISTS_PK         PRIMARY KEY (CHECKLIST_ID),
  CONSTRAINT EMP_DOC_CHECKLISTS_STATUS_CHK CHECK       (STATUS IN ('Pending','Submitted','Approved','Waived')),
  CONSTRAINT EMP_DOC_CHECKLISTS_EMP_FK     FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)           ON DELETE CASCADE,
  CONSTRAINT EMP_DOC_CHECKLISTS_DOC_FK     FOREIGN KEY (DOCUMENT_ID) REFERENCES EMPLOYEE_DOCUMENTS(DOCUMENT_ID)  ON DELETE SET NULL
);

-- ============================================================
-- 20. AUDIT_LOGS
-- ============================================================
CREATE TABLE AUDIT_LOGS (
  LOG_ID        NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  USER_ID       NUMBER(10),
  ACTION_NAME   VARCHAR2(100) NOT NULL,
  MODULE_NAME   VARCHAR2(80)  NOT NULL,
  MODEL_ID      NUMBER(10),
  LOG_DATA      CLOB,
  IP_ADDRESS    VARCHAR2(45),
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT AUDIT_LOGS_PK       PRIMARY KEY (LOG_ID),
  CONSTRAINT AUDIT_LOGS_USER_FK  FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNTS(USER_ID) ON DELETE SET NULL
);

-- ============================================================
-- 21. SYSTEM_NOTIFICATIONS
-- ============================================================
CREATE TABLE SYSTEM_NOTIFICATIONS (
  NOTIFICATION_ID NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  USER_ID         NUMBER(10)    NOT NULL,
  NOTIF_TYPE      VARCHAR2(10)  DEFAULT 'info' NOT NULL,
  TITLE           VARCHAR2(200) NOT NULL,
  MESSAGE         CLOB          NOT NULL,
  LINK            VARCHAR2(500),
  IS_READ         NUMBER(1)     DEFAULT 0 NOT NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT SYSTEM_NOTIFICATIONS_PK        PRIMARY KEY (NOTIFICATION_ID),
  CONSTRAINT SYSTEM_NOTIFICATIONS_TYPE_CHK  CHECK       (NOTIF_TYPE IN ('info','success','warning','danger')),
  CONSTRAINT SYSTEM_NOTIFICATIONS_USER_FK   FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNTS(USER_ID) ON DELETE CASCADE
);

-- ============================================================
-- 22. LMS_MODULES
-- ============================================================
CREATE TABLE LMS_MODULES (
  MODULE_ID       NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  TITLE           VARCHAR2(200) NOT NULL,
  DESCRIPTION     CLOB,
  MODULE_TYPE     VARCHAR2(15)  DEFAULT 'document' NOT NULL,
  DURATION_MINS   NUMBER(6)     DEFAULT 0 NOT NULL,
  DEPARTMENT_ID   NUMBER(10),
  CREATED_BY      NUMBER(10),
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT LMS_MODULES_PK        PRIMARY KEY (MODULE_ID),
  CONSTRAINT LMS_MODULES_TYPE_CHK  CHECK       (MODULE_TYPE IN ('document','video','quiz')),
  CONSTRAINT LMS_MODULES_DEPT_FK   FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)  ON DELETE SET NULL,
  CONSTRAINT LMS_MODULES_USER_FK   FOREIGN KEY (CREATED_BY)    REFERENCES USER_ACCOUNTS(USER_ID)      ON DELETE SET NULL
);

-- ============================================================
-- 23. LMS_ENROLLMENTS
-- ============================================================
CREATE TABLE LMS_ENROLLMENTS (
  ENROLLMENT_ID   NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  MODULE_ID       NUMBER(10)   NOT NULL,
  EMPLOYEE_ID     NUMBER(10)   NOT NULL,
  PROGRESS        NUMBER(3)    DEFAULT 0 NOT NULL,
  STATUS          VARCHAR2(15) DEFAULT 'Not Started' NOT NULL,
  COMPLETED_AT    NUMBER(12),
  CREATED_AT      NUMBER(12)   DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT LMS_ENROLLMENTS_PK          PRIMARY KEY (ENROLLMENT_ID),
  CONSTRAINT LMS_ENROLLMENTS_UQ          UNIQUE      (MODULE_ID, EMPLOYEE_ID),
  CONSTRAINT LMS_ENROLLMENTS_STATUS_CHK  CHECK       (STATUS IN ('Not Started','In Progress','Completed')),
  CONSTRAINT LMS_ENROLLMENTS_MOD_FK      FOREIGN KEY (MODULE_ID)   REFERENCES LMS_MODULES(MODULE_ID) ON DELETE CASCADE,
  CONSTRAINT LMS_ENROLLMENTS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 24. JOB_POSTINGS
-- ============================================================
CREATE TABLE JOB_POSTINGS (
  JOB_ID          NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  TITLE           VARCHAR2(150) NOT NULL,
  DEPARTMENT_ID   NUMBER(10),
  DESCRIPTION     CLOB,
  REQUIREMENTS    CLOB,
  SALARY_MIN      NUMBER(12,2),
  SALARY_MAX      NUMBER(12,2),
  LOCATION        VARCHAR2(150),
  JOB_TYPE        VARCHAR2(40),
  STATUS          VARCHAR2(10)  DEFAULT 'Open' NOT NULL,
  POSTED_BY       NUMBER(10),
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT JOB_POSTINGS_PK          PRIMARY KEY (JOB_ID),
  CONSTRAINT JOB_POSTINGS_STATUS_CHK  CHECK       (STATUS IN ('Open','Closed','On Hold')),
  CONSTRAINT JOB_POSTINGS_DEPT_FK     FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL,
  CONSTRAINT JOB_POSTINGS_USER_FK     FOREIGN KEY (POSTED_BY)     REFERENCES USER_ACCOUNTS(USER_ID)     ON DELETE SET NULL
);

-- ============================================================
-- 25. CANDIDATES
-- ============================================================
CREATE TABLE CANDIDATES (
  CANDIDATE_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  JOB_ID          NUMBER(10)    NOT NULL,
  CANDIDATE_NAME  VARCHAR2(150) NOT NULL,
  EMAIL           VARCHAR2(150),
  PHONE           VARCHAR2(30),
  STAGE           VARCHAR2(15)  DEFAULT 'Applied' NOT NULL,
  EXPECTED_SALARY NUMBER(12,2),
  APPLIED_AT      DATE,
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT CANDIDATES_PK          PRIMARY KEY (CANDIDATE_ID),
  CONSTRAINT CANDIDATES_STAGE_CHK   CHECK       (STAGE IN ('Applied','Screening','Interview','Offer','Hired','Rejected')),
  CONSTRAINT CANDIDATES_JOB_FK      FOREIGN KEY (JOB_ID) REFERENCES JOB_POSTINGS(JOB_ID) ON DELETE CASCADE
);

-- ============================================================
-- 26. PROJECTS
-- ============================================================
CREATE TABLE PROJECTS (
  PROJECT_ID      NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  PROJECT_NAME    VARCHAR2(150) NOT NULL,
  OWNER_ID        NUMBER(10),
  DEPARTMENT_ID   NUMBER(10),
  DESCRIPTION     CLOB,
  START_DATE      DATE,
  DEADLINE        DATE,
  STATUS          VARCHAR2(15)  DEFAULT 'Active' NOT NULL,
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT PROJECTS_PK          PRIMARY KEY (PROJECT_ID),
  CONSTRAINT PROJECTS_STATUS_CHK  CHECK       (STATUS IN ('Active','On Hold','Completed','Cancelled')),
  CONSTRAINT PROJECTS_OWNER_FK    FOREIGN KEY (OWNER_ID)      REFERENCES EMPLOYEES(EMPLOYEE_ID)     ON DELETE SET NULL,
  CONSTRAINT PROJECTS_DEPT_FK     FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
);

-- ============================================================
-- 27. PROJECT_MEMBERS
-- ============================================================
CREATE TABLE PROJECT_MEMBERS (
  MEMBER_ID     NUMBER(10) GENERATED ALWAYS AS IDENTITY,
  PROJECT_ID    NUMBER(10) NOT NULL,
  EMPLOYEE_ID   NUMBER(10) NOT NULL,
  CONSTRAINT PROJECT_MEMBERS_PK       PRIMARY KEY (MEMBER_ID),
  CONSTRAINT PROJECT_MEMBERS_UQ       UNIQUE      (PROJECT_ID, EMPLOYEE_ID),
  CONSTRAINT PROJECT_MEMBERS_PROJ_FK  FOREIGN KEY (PROJECT_ID)  REFERENCES PROJECTS(PROJECT_ID)   ON DELETE CASCADE,
  CONSTRAINT PROJECT_MEMBERS_EMP_FK   FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 28. PROJECT_TASKS
-- ============================================================
CREATE TABLE PROJECT_TASKS (
  TASK_ID       NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  PROJECT_ID    NUMBER(10)    NOT NULL,
  EMPLOYEE_ID   NUMBER(10),
  TITLE         VARCHAR2(200) NOT NULL,
  PRIORITY      VARCHAR2(10)  DEFAULT 'Medium' NOT NULL,
  STATUS        VARCHAR2(15)  DEFAULT 'To Do'  NOT NULL,
  PROGRESS      NUMBER(3)     DEFAULT 0 NOT NULL,
  DUE_DATE      DATE,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT PROJECT_TASKS_PK          PRIMARY KEY (TASK_ID),
  CONSTRAINT PROJECT_TASKS_PRIO_CHK    CHECK       (PRIORITY IN ('Low','Medium','High','Critical')),
  CONSTRAINT PROJECT_TASKS_STATUS_CHK  CHECK       (STATUS   IN ('To Do','In Progress','Completed','Cancelled')),
  CONSTRAINT PROJECT_TASKS_PROJ_FK     FOREIGN KEY (PROJECT_ID)  REFERENCES PROJECTS(PROJECT_ID)   ON DELETE CASCADE,
  CONSTRAINT PROJECT_TASKS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL
);

-- ============================================================
-- INDEXES — Part 2
-- ============================================================
CREATE INDEX EMP_DOC_CHK_EMP_IDX      ON EMPLOYEE_DOC_CHECKLISTS(EMPLOYEE_ID);
CREATE INDEX EMP_DOC_CHK_STATUS_IDX   ON EMPLOYEE_DOC_CHECKLISTS(STATUS);
CREATE INDEX EMP_DOC_EMP_IDX          ON EMPLOYEE_DOCUMENTS(EMPLOYEE_ID);
CREATE INDEX AUDIT_USER_IDX           ON AUDIT_LOGS(USER_ID);
CREATE INDEX AUDIT_MOD_IDX            ON AUDIT_LOGS(MODULE_NAME);
CREATE INDEX NOTIF_USER_IDX           ON SYSTEM_NOTIFICATIONS(USER_ID);
CREATE INDEX NOTIF_READ_IDX           ON SYSTEM_NOTIFICATIONS(USER_ID, IS_READ);
CREATE INDEX LMS_ENROLL_EMP_IDX       ON LMS_ENROLLMENTS(EMPLOYEE_ID);
CREATE INDEX CANDIDATES_JOB_IDX       ON CANDIDATES(JOB_ID);
CREATE INDEX PROJ_TASKS_PROJ_IDX      ON PROJECT_TASKS(PROJECT_ID);

