-- ============================================================
--  Staffora HRMS v3 — Oracle DDL (Part 2 / 2)
--  Relational Model | Oracle Database 21c
-- ============================================================

-- ============================================================
-- 15. BENEFITS
-- ============================================================
CREATE TABLE BENEFITS (
  BENEFIT_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  BENEFIT_NAME  VARCHAR2(100) NOT NULL,
  DESCRIPTION   CLOB,
  BENEFIT_TYPE  VARCHAR2(50)  DEFAULT 'Other' NOT NULL,
  VALUE         NUMBER(12,2)  DEFAULT 0 NOT NULL,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT BENEFITS_PK           PRIMARY KEY (BENEFIT_ID),
  CONSTRAINT BENEFITS_NAME_UQ      UNIQUE      (BENEFIT_NAME),
  CONSTRAINT BENEFITS_TYPE_CHK     CHECK       (BENEFIT_TYPE IN ('Health','Government','Bonus','Allowance','Other'))
);

-- ============================================================
-- 16. EMPLOYEE_BENEFITS
-- ============================================================
CREATE TABLE EMPLOYEE_BENEFITS (
  EMP_BENEFIT_ID  NUMBER(10) GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID     NUMBER(10) NOT NULL,
  BENEFIT_ID      NUMBER(10) NOT NULL,
  ENROLLED_AT     DATE,
  CONSTRAINT EMPLOYEE_BENEFITS_PK      PRIMARY KEY (EMP_BENEFIT_ID),
  CONSTRAINT EMPLOYEE_BENEFITS_UQ      UNIQUE      (EMPLOYEE_ID, BENEFIT_ID),
  CONSTRAINT EMPLOYEE_BENEFITS_EMP_FK  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE,
  CONSTRAINT EMPLOYEE_BENEFITS_BEN_FK  FOREIGN KEY (BENEFIT_ID)  REFERENCES BENEFITS(BENEFIT_ID)   ON DELETE CASCADE
);

-- ============================================================
-- 17. ONBOARDING_TASKS
-- ============================================================
CREATE TABLE ONBOARDING_TASKS (
  TASK_ID       NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)    NOT NULL,
  TASK_NAME     VARCHAR2(200) NOT NULL,
  STAGE         VARCHAR2(20)  DEFAULT 'Pre-boarding' NOT NULL,
  STATUS        VARCHAR2(20)  DEFAULT 'Not Started'  NOT NULL,
  DUE_DATE      DATE,
  NOTES         CLOB,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT ONBOARDING_TASKS_PK          PRIMARY KEY (TASK_ID),
  CONSTRAINT ONBOARDING_TASKS_STAGE_CHK   CHECK       (STAGE  IN ('Pre-boarding','Week 1','Week 2','Integration')),
  CONSTRAINT ONBOARDING_TASKS_STATUS_CHK  CHECK       (STATUS IN ('Not Started','In Progress','Completed','On Hold')),
  CONSTRAINT ONBOARDING_TASKS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 18. EMPLOYEE_DOCUMENTS
-- ============================================================
CREATE TABLE EMPLOYEE_DOCUMENTS (
  DOCUMENT_ID   NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)    NOT NULL,
  DOCUMENT_TYPE VARCHAR2(100) NOT NULL,
  FILE_NAME     VARCHAR2(255) NOT NULL,
  FILE_PATH     VARCHAR2(500) NOT NULL,
  UPLOADED_AT   NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT EMPLOYEE_DOCUMENTS_PK      PRIMARY KEY (DOCUMENT_ID),
  CONSTRAINT EMPLOYEE_DOCUMENTS_EMP_FK  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 19. EMPLOYEE_DOC_CHECKLISTS
-- ============================================================
CREATE TABLE EMPLOYEE_DOC_CHECKLISTS (
  CHECKLIST_ID  NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  EMPLOYEE_ID   NUMBER(10)    NOT NULL,
  DOCUMENT_TYPE VARCHAR2(100) NOT NULL,
  STATUS        VARCHAR2(15)  DEFAULT 'Pending' NOT NULL,
  DOCUMENT_ID   NUMBER(10),
  NOTES         VARCHAR2(255),
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT EMP_DOC_CHECKLISTS_PK         PRIMARY KEY (CHECKLIST_ID),
  CONSTRAINT EMP_DOC_CHECKLISTS_STATUS_CHK CHECK       (STATUS IN ('Pending','Submitted','Approved','Waived')),
  CONSTRAINT EMP_DOC_CHECKLISTS_EMP_FK     FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)           ON DELETE CASCADE,
  CONSTRAINT EMP_DOC_CHECKLISTS_DOC_FK     FOREIGN KEY (DOCUMENT_ID) REFERENCES EMPLOYEE_DOCUMENTS(DOCUMENT_ID)  ON DELETE SET NULL
);

-- ============================================================
-- 20. AUDIT_LOGS
-- ============================================================
CREATE TABLE AUDIT_LOGS (
  LOG_ID        NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  USER_ID       NUMBER(10),
  ACTION_NAME   VARCHAR2(100) NOT NULL,
  MODULE_NAME   VARCHAR2(80)  NOT NULL,
  MODEL_ID      NUMBER(10),
  LOG_DATA      CLOB,
  IP_ADDRESS    VARCHAR2(45),
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT AUDIT_LOGS_PK       PRIMARY KEY (LOG_ID),
  CONSTRAINT AUDIT_LOGS_USER_FK  FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNTS(USER_ID) ON DELETE SET NULL
);

-- ============================================================
-- 21. SYSTEM_NOTIFICATIONS
-- ============================================================
CREATE TABLE SYSTEM_NOTIFICATIONS (
  NOTIFICATION_ID NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  USER_ID         NUMBER(10)    NOT NULL,
  NOTIF_TYPE      VARCHAR2(10)  DEFAULT 'info' NOT NULL,
  TITLE           VARCHAR2(200) NOT NULL,
  MESSAGE         CLOB          NOT NULL,
  LINK            VARCHAR2(500),
  IS_READ         NUMBER(1)     DEFAULT 0 NOT NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT SYSTEM_NOTIFICATIONS_PK        PRIMARY KEY (NOTIFICATION_ID),
  CONSTRAINT SYSTEM_NOTIFICATIONS_TYPE_CHK  CHECK       (NOTIF_TYPE IN ('info','success','warning','danger')),
  CONSTRAINT SYSTEM_NOTIFICATIONS_USER_FK   FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNTS(USER_ID) ON DELETE CASCADE
);

-- ============================================================
-- 22. LMS_MODULES
-- ============================================================
CREATE TABLE LMS_MODULES (
  MODULE_ID       NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  TITLE           VARCHAR2(200) NOT NULL,
  DESCRIPTION     CLOB,
  MODULE_TYPE     VARCHAR2(15)  DEFAULT 'document' NOT NULL,
  DURATION_MINS   NUMBER(6)     DEFAULT 0 NOT NULL,
  DEPARTMENT_ID   NUMBER(10),
  CREATED_BY      NUMBER(10),
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT LMS_MODULES_PK        PRIMARY KEY (MODULE_ID),
  CONSTRAINT LMS_MODULES_TYPE_CHK  CHECK       (MODULE_TYPE IN ('document','video','quiz')),
  CONSTRAINT LMS_MODULES_DEPT_FK   FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)  ON DELETE SET NULL,
  CONSTRAINT LMS_MODULES_USER_FK   FOREIGN KEY (CREATED_BY)    REFERENCES USER_ACCOUNTS(USER_ID)      ON DELETE SET NULL
);

-- ============================================================
-- 23. LMS_ENROLLMENTS
-- ============================================================
CREATE TABLE LMS_ENROLLMENTS (
  ENROLLMENT_ID   NUMBER(10)   GENERATED ALWAYS AS IDENTITY,
  MODULE_ID       NUMBER(10)   NOT NULL,
  EMPLOYEE_ID     NUMBER(10)   NOT NULL,
  PROGRESS        NUMBER(3)    DEFAULT 0 NOT NULL,
  STATUS          VARCHAR2(15) DEFAULT 'Not Started' NOT NULL,
  COMPLETED_AT    NUMBER(12),
  CREATED_AT      NUMBER(12)   DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)   DEFAULT 0 NOT NULL,
  CONSTRAINT LMS_ENROLLMENTS_PK          PRIMARY KEY (ENROLLMENT_ID),
  CONSTRAINT LMS_ENROLLMENTS_UQ          UNIQUE      (MODULE_ID, EMPLOYEE_ID),
  CONSTRAINT LMS_ENROLLMENTS_STATUS_CHK  CHECK       (STATUS IN ('Not Started','In Progress','Completed')),
  CONSTRAINT LMS_ENROLLMENTS_MOD_FK      FOREIGN KEY (MODULE_ID)   REFERENCES LMS_MODULES(MODULE_ID) ON DELETE CASCADE,
  CONSTRAINT LMS_ENROLLMENTS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 24. JOB_POSTINGS
-- ============================================================
CREATE TABLE JOB_POSTINGS (
  JOB_ID          NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  TITLE           VARCHAR2(150) NOT NULL,
  DEPARTMENT_ID   NUMBER(10),
  DESCRIPTION     CLOB,
  REQUIREMENTS    CLOB,
  SALARY_MIN      NUMBER(12,2),
  SALARY_MAX      NUMBER(12,2),
  LOCATION        VARCHAR2(150),
  JOB_TYPE        VARCHAR2(40),
  STATUS          VARCHAR2(10)  DEFAULT 'Open' NOT NULL,
  POSTED_BY       NUMBER(10),
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT JOB_POSTINGS_PK          PRIMARY KEY (JOB_ID),
  CONSTRAINT JOB_POSTINGS_STATUS_CHK  CHECK       (STATUS IN ('Open','Closed','On Hold')),
  CONSTRAINT JOB_POSTINGS_DEPT_FK     FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL,
  CONSTRAINT JOB_POSTINGS_USER_FK     FOREIGN KEY (POSTED_BY)     REFERENCES USER_ACCOUNTS(USER_ID)     ON DELETE SET NULL
);

-- ============================================================
-- 25. CANDIDATES
-- ============================================================
CREATE TABLE CANDIDATES (
  CANDIDATE_ID    NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  JOB_ID          NUMBER(10)    NOT NULL,
  CANDIDATE_NAME  VARCHAR2(150) NOT NULL,
  EMAIL           VARCHAR2(150),
  PHONE           VARCHAR2(30),
  STAGE           VARCHAR2(15)  DEFAULT 'Applied' NOT NULL,
  EXPECTED_SALARY NUMBER(12,2),
  APPLIED_AT      DATE,
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT CANDIDATES_PK          PRIMARY KEY (CANDIDATE_ID),
  CONSTRAINT CANDIDATES_STAGE_CHK   CHECK       (STAGE IN ('Applied','Screening','Interview','Offer','Hired','Rejected')),
  CONSTRAINT CANDIDATES_JOB_FK      FOREIGN KEY (JOB_ID) REFERENCES JOB_POSTINGS(JOB_ID) ON DELETE CASCADE
);

-- ============================================================
-- 26. PROJECTS
-- ============================================================
CREATE TABLE PROJECTS (
  PROJECT_ID      NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  PROJECT_NAME    VARCHAR2(150) NOT NULL,
  OWNER_ID        NUMBER(10),
  DEPARTMENT_ID   NUMBER(10),
  DESCRIPTION     CLOB,
  START_DATE      DATE,
  DEADLINE        DATE,
  STATUS          VARCHAR2(15)  DEFAULT 'Active' NOT NULL,
  CREATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  UPDATED_AT      NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT PROJECTS_PK          PRIMARY KEY (PROJECT_ID),
  CONSTRAINT PROJECTS_STATUS_CHK  CHECK       (STATUS IN ('Active','On Hold','Completed','Cancelled')),
  CONSTRAINT PROJECTS_OWNER_FK    FOREIGN KEY (OWNER_ID)      REFERENCES EMPLOYEES(EMPLOYEE_ID)     ON DELETE SET NULL,
  CONSTRAINT PROJECTS_DEPT_FK     FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
);

-- ============================================================
-- 27. PROJECT_MEMBERS
-- ============================================================
CREATE TABLE PROJECT_MEMBERS (
  MEMBER_ID     NUMBER(10) GENERATED ALWAYS AS IDENTITY,
  PROJECT_ID    NUMBER(10) NOT NULL,
  EMPLOYEE_ID   NUMBER(10) NOT NULL,
  CONSTRAINT PROJECT_MEMBERS_PK       PRIMARY KEY (MEMBER_ID),
  CONSTRAINT PROJECT_MEMBERS_UQ       UNIQUE      (PROJECT_ID, EMPLOYEE_ID),
  CONSTRAINT PROJECT_MEMBERS_PROJ_FK  FOREIGN KEY (PROJECT_ID)  REFERENCES PROJECTS(PROJECT_ID)   ON DELETE CASCADE,
  CONSTRAINT PROJECT_MEMBERS_EMP_FK   FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE
);

-- ============================================================
-- 28. PROJECT_TASKS
-- ============================================================
CREATE TABLE PROJECT_TASKS (
  TASK_ID       NUMBER(10)    GENERATED ALWAYS AS IDENTITY,
  PROJECT_ID    NUMBER(10)    NOT NULL,
  EMPLOYEE_ID   NUMBER(10),
  TITLE         VARCHAR2(200) NOT NULL,
  PRIORITY      VARCHAR2(10)  DEFAULT 'Medium' NOT NULL,
  STATUS        VARCHAR2(15)  DEFAULT 'To Do'  NOT NULL,
  PROGRESS      NUMBER(3)     DEFAULT 0 NOT NULL,
  DUE_DATE      DATE,
  CREATED_AT    NUMBER(12)    DEFAULT 0 NOT NULL,
  CONSTRAINT PROJECT_TASKS_PK          PRIMARY KEY (TASK_ID),
  CONSTRAINT PROJECT_TASKS_PRIO_CHK    CHECK       (PRIORITY IN ('Low','Medium','High','Critical')),
  CONSTRAINT PROJECT_TASKS_STATUS_CHK  CHECK       (STATUS   IN ('To Do','In Progress','Completed','Cancelled')),
  CONSTRAINT PROJECT_TASKS_PROJ_FK     FOREIGN KEY (PROJECT_ID)  REFERENCES PROJECTS(PROJECT_ID)   ON DELETE CASCADE,
  CONSTRAINT PROJECT_TASKS_EMP_FK      FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL
);

-- ============================================================
-- INDEXES — Part 2
-- ============================================================
CREATE INDEX EMP_DOC_CHK_EMP_IDX      ON EMPLOYEE_DOC_CHECKLISTS(EMPLOYEE_ID);
CREATE INDEX EMP_DOC_CHK_STATUS_IDX   ON EMPLOYEE_DOC_CHECKLISTS(STATUS);
CREATE INDEX EMP_DOC_EMP_IDX          ON EMPLOYEE_DOCUMENTS(EMPLOYEE_ID);
CREATE INDEX AUDIT_USER_IDX           ON AUDIT_LOGS(USER_ID);
CREATE INDEX AUDIT_MOD_IDX            ON AUDIT_LOGS(MODULE_NAME);
CREATE INDEX NOTIF_USER_IDX           ON SYSTEM_NOTIFICATIONS(USER_ID);
CREATE INDEX NOTIF_READ_IDX           ON SYSTEM_NOTIFICATIONS(USER_ID, IS_READ);
CREATE INDEX LMS_ENROLL_EMP_IDX       ON LMS_ENROLLMENTS(EMPLOYEE_ID);
CREATE INDEX CANDIDATES_JOB_IDX       ON CANDIDATES(JOB_ID);
CREATE INDEX PROJ_TASKS_PROJ_IDX      ON PROJECT_TASKS(PROJECT_ID);

-- ============================================================
-- END OF SCHEMA
-- ============================================================
